### ISSUE TITLE
# Login Method

### ISSUE THREAD

**Issue by vishal035** [vishal035/learning-mongoDB#3]
The Loging Path is not working correctly...

Here is the console log

```

-Login Error: ReferenceError: User is not defined
    at Function.userSchema.statics.findByCredentials (D:\Development\JavaScript\Learning\task manager\src\models\users.js:55:18)
    at D:\Development\JavaScript\Learning\task manager\src\routers\users.js:8:33
    at Layer.handle [as handle_request] (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\layer.js:95:5)
    at D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:317:13)
    at D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\index.js:275:10)

```

**Comment by vishal035** [comment]
Problem Solved..✅
