### ISSUE TITLE
# Error while getting the task when user is loged-in

### ISSUE THREAD

**Issue by vishal035** [vishal035/learning-mongoDB#6]
- Log Message:

```
Server is up on 3000
GET /tasks
MissingSchemaError: Schema hasn't been registered for model "Task".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\connection.js:1242:11)
    at getModelsMapForPopulate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:300:59)        
    at populate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\model.js:4323:21)
    at _populate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\model.js:4293:5)
    at D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\model.js:4269:5
    at promiseOrCallback (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\helpers\promiseOrCallback.js:9:12)
    at Mongoose._promiseOrCallback (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\index.js:1135:10)
    at Function.Model.populate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\model.js:4267:23)
    at model.populate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\document.js:3893:19)
    at D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\document.js:3943:10
    at D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at model.Document.execPopulate (D:\Development\JavaScript\Learning\task manager\node_modules\mongoose\lib\document.js:3942:10)
    at D:\Development\JavaScript\Learning\task manager\src\routers\tasks.js:23:38
    at Layer.handle [as handle_request] (D:\Development\JavaScript\Learning\task manager\node_modules\express\lib\router\layer.js:95:5)

```

**Comment by vishal035** [comment]
Error Solved with the populating the task data to virtual field
